### PR TITLE
runtime check without secrets

### PR DESCRIPTION
**Pull request by Necktschnagge**
## Changes so far:
* chmod +x *.sh
* fix json initialization bug
* add some runtime check to Linux ci

## original issue:

@r0ost3r reported that there is some runtime exception when executing under Linux.
```
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::type_error'
  what():  [json.exception.type_error.305] cannot use operator[] with a string argument with array
```

Let's have a look.

### CODE REVIEW

**Comment by Necktschnagge** [comment]
Maybe creating an empty json results in an empty array.

**Comment by Necktschnagge** [comment]
[9576f53](https://github.com/Necktschnagge/finn/pull/16/commits/9576f531de086ad3f2ce3485550fc8bcb0681d2e) looks like it already crashes before returning empty summary json.
The log by @r0ost3r looked differently.

has to be debugged locally in Linux.

**Comment by Necktschnagge** [comment]
Reason for creating in array is `{}`-initialization. See:
* https://github.com/nlohmann/json/discussions/3061
* https://json.nlohmann.me/home/faq/

**Comment by Necktschnagge** [comment]
@r0ost3r please check if this solves your issue on Linux.
You may use "Squash and merge" button afterwards if you like.

**Comment by r0ost3r** [comment]
Linux issue fixed.

**Pull request merged**
